### ISSUE TITLE
Direct replacement doesn't work

### ISSUE THREAD

**Issue by fly3110** [lofcz/sweetalert2-neutral#6]
### Current behavior

After uninstalling sweetalert2 and installing this version, I receive an error:

`Failed to resolve import "sweetalert2" from "src/App.vue". Does the file exist?`

### Expected behavior

Everything works as before

### Live demo !!! THIS FIELD IS REQUIRED !!!

https://github.com/fly3110/sweetaler2-neutral-issue

It works if I replace `import Swal from 'sweetalert2';` to `import Swal from 'sweetalert2-neutral';`, but WebStorm complains about type declarations: `Vue: Could not find a declaration file for module sweetalert2-neutral.`

**Comment by fly3110** [comment]
And some more.

If I want to import just javascript (which worked with sweetalert2) using 
`import Swal from 'sweetalert2-neutral/dist/sweetalert2';`
`import Swal from 'sweetalert2-neutral/dist/sweetalert2.all';`
`import Swal from 'sweetalert2-neutral/dist/sweetalert2.esm';`
`import Swal from 'sweetalert2-neutral/dist/sweetalert2.min';`,

 I receive an error:  `[plugin:vite:import-analysis] Missing "./dist/sweetalert2" specifier in "sweetalert2-neutral" package`

**Comment by lofcz** [comment]
Sorry about the issue and thanks for the repro - I believe this is fixed now, could you do the two minor things I did to your repro and verify whether that resolves the issue? https://github.com/lofcz/sweetaler2-neutral-issue/commit/16a311a0010584c169561bcf0b373e84bd8b89c9

**Comment by lofcz** [comment]
Added missing css export in `sweetalert2-neutral@11.14.1-neutral-fix6` (available on npm now)

**Comment by fly3110** [comment]
You rock! Thanks!
